static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: httpbin_stats
          route_config:
            name: local_route
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service_python
              - match:
                  prefix: "/service1"
                route:
                  cluster: service_python
          http_filters:
          - name: envoy.filters.http.router
  clusters:
  - name: service_python
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_python
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: 7771
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: 7772
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: 7773
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: 7774
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901